import { ProductType, ProductInfo } from './types';

/**
 * Helper para derivar unidad de peso desde el campo Máster
 */

/**
 * Helper para derivar unidad de peso desde el campo Máster
 */
function deriveUnit(master: string): 'KG' | 'LB' {
    const masterLower = master.toLowerCase();
    if (masterLower.includes(' lb') || masterLower.includes('lb ')) {
        return 'LB';
    }
    return 'KG'; // Default a KG
}

/**
 * Diccionario de productos - Códigos 00010-00517
 */
export const PRODUCT_DATA: Record<string, ProductInfo> = {
    '00010': { client: 'OPTIMIZE INTEGRATION GROUP INC.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00012': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00016': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 4 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 4 Lb') },
    '00017': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 4 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 4 Lb') },
    '00018': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 4 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 4 Lb') },
    '00020': { client: 'ZHEJIANG YIWU CHINA COMMODITY CITY IMPOR', type: 'COLA', master: '10 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 2 Kg') },
    '00021': { client: 'ZHEJIANG YIWU CHINA COMMODITY CITY IMPOR', type: 'COLA', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00022': { client: 'OPTIMIZE INTEGRATION GROUP INC.', type: 'ENTERO', master: '10 Und * 1.4 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 1.4 Kg') },
    '00024': { client: 'TIANJIN YINGBIN SUPPLY CHAIN CO., LTD', type: 'COLA', master: '10 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 2 Kg') },
    '00026': { client: 'PESCANOVA INC', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'SUNDAYS BEST', unit: deriveUnit('10 Und * 4 Lb') },
    '00027': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00028': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00034': { client: 'BLUE PACIFIC LLC', type: 'ENTERO', master: '10 Und * 3.92 Lb', brand: 'MAJESTIC', unit: deriveUnit('10 Und * 3.92 Lb') },
    '00035': { client: 'CASMARK SEAFOODS LTD', type: 'ENTERO', master: '6 Und * 4 Lb', brand: 'AQUAGOLD', unit: deriveUnit('6 Und * 4 Lb') },
    '00036': { client: 'INTEROCEAN SEAFOOD TRADER INC', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'BAY RIVER', unit: deriveUnit('10 Und * 4 Lb') },
    '00037': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'ENTERO', master: '6 Und * 1.85 Kg', brand: 'OCEAN', unit: deriveUnit('6 Und * 1.85 Kg') },
    '00039': { client: 'INTERATLANTIC FISH S.L.U.', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00041': { client: 'BLUE PACIFIC LLC', type: 'COLA', master: '10 Und * 3.84 Lb', brand: 'MAJESTIC', unit: deriveUnit('10 Und * 3.84 Lb') },
    '00042': { client: 'INTEROCEAN SEAFOOD TRADER INC', type: 'COLA', master: '10 Und * 4 Lb', brand: 'BAY RIVER', unit: deriveUnit('10 Und * 4 Lb') },
    '00043': { client: 'IMAEX TRADING CO. INC.', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'BEAUTY WING', unit: deriveUnit('10 Und * 4 Lb') },
    '00044': { client: 'PESCANOVA INC', type: 'COLA', master: '10 Und * 4 Lb', brand: 'SUNDAYS BEST', unit: deriveUnit('10 Und * 4 Lb') },
    '00045': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 4 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 4 Lb') },
    '00046': { client: 'AZ GEMS INC.', type: 'COLA', master: '6 Und * 4 Lb', brand: 'AQUA GEMS', unit: deriveUnit('6 Und * 4 Lb') },
    '00047': { client: 'FOOD MASTERS', type: 'ENTERO', master: '10 Und * 1.4 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 1.4 Kg') },
    '00048': { client: 'SN TRADING', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00049': { client: 'SCARPA WORLDWIDE LIMITED', type: 'COLA', master: '10 Und * 4 Lb', brand: 'SOUTHERN SEAS', unit: deriveUnit('10 Und * 4 Lb') },
    '00050': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'VALOR_AGREGADO', master: '1 Und * 40 Lb', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 40 Lb') },
    '00051': { client: 'MAISON MER', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00052': { client: 'SIORAS NIKITAS & CO', type: 'ENTERO', master: '3 Und * 4 Kg', brand: 'VITAGULF', unit: deriveUnit('3 Und * 4 Kg') },
    '00053': { client: 'AZ GEMS INC.', type: 'COLA', master: '10 Und * 4 Lb', brand: 'AQUA GEMS', unit: deriveUnit('10 Und * 4 Lb') },
    '00054': { client: 'OCEAN GARDEN', type: 'COLA', master: '6 Und * 5 Lb', brand: 'OCEAN GARDEN', unit: deriveUnit('6 Und * 5 Lb') },
    '00055': { client: 'ACADIAN FISH CO', type: 'COLA', master: '10 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 4 Lb') },
    '00056': { client: 'MARUHA NICHIRO CORPORATION', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('6 Und * 2 Kg') },
    '00057': { client: 'SI2A', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 2 Kg') },
    '00058': { client: 'SCARPA WORLDWIDE LIMITED', type: 'COLA', master: '10 Und * 4 Lb', brand: 'CAMARON KING', unit: deriveUnit('10 Und * 4 Lb') },
    '00059': { client: 'CH. J. PANTAZIS S. A.', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('6 Und * 2 Kg') },
    '00060': { client: 'EVERGLORY INT TRADING (SA) CC', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00062': { client: 'DISTRIBUIDORA CAMAVINGA SA DE CV', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 12 Kg') },
    '00063': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00064': { client: 'FRESH&GOOD OÜ', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00065': { client: 'Monarch Trading, LLC', type: 'COLA', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00066': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00067': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00068': { client: 'SN TRADING', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00069': { client: 'MAISON MER', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00070': { client: 'EVERGLORY INT TRADING (SA) CC', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00071': { client: 'CASMARK SEAFOODS LTD', type: 'ENTERO', master: '6 Und * 4 Lb', brand: 'CK', unit: deriveUnit('6 Und * 4 Lb') },
    '00072': { client: 'SOUTHWIND FOODS', type: 'COLA', master: '6 Und * 4 Lb', brand: 'TERRASEA', unit: deriveUnit('6 Und * 4 Lb') },
    '00073': { client: 'GUANGDONG HONGBAO AQUATIC DEVELOPMENT', type: 'COLA', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00074': { client: 'Hengsheng Heyuan Economic and trade', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'VITAGULF', unit: deriveUnit('1 Und * 12 Kg') },
    '00075': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 4 Lb') },
    '00076': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 1.814 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.814 Kg') },
    '00077': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00078': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 1.814 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.814 Kg') },
    '00079': { client: 'COCEDERO DE MARISCOS', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00081': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00082': { client: 'NV HOTTLET FROZEN FOODS', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'VITAGULF', unit: deriveUnit('6 Und * 2 Kg') },
    '00083': { client: 'H&N GROUP', type: 'COLA', master: '10 Und * 4 Lb', brand: 'BLUE RIVER', unit: deriveUnit('10 Und * 4 Lb') },
    '00084': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00085': { client: 'SI2A', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00087': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '6 Und * 1.65 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 1.65 Kg') },
    '00088': { client: 'METRO A.D. EXPORT-IMPORT SKOPJE', type: 'ENTERO', master: '10 Und * 1.8 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 1.8 Kg') },
    '00089': { client: 'NAUTILUS SEAFOOD', type: 'COLA', master: '10 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 4 Lb') },
    '00091': { client: 'Monarch Trading, LLC', type: 'COLA', master: '10 Und * 4 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 4 Lb') },
    '00092': { client: 'MARUHA NICHIRO CORPORATION', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('6 Und * 2 Kg') },
    '00093': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'VALOR_AGREGADO', master: '12 Und * 0.80 Kg', brand: 'OCEAN', unit: deriveUnit('12 Und * 0.80 Kg') },
    '00094': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'VALOR_AGREGADO', master: '12 Und * 0.80 Kg', brand: 'OCEAN', unit: deriveUnit('12 Und * 0.80 Kg') },
    '00095': { client: 'NV HOTTLET FROZEN FOODS', type: 'ENTERO', master: '12 Und * 0.80 Kg', brand: 'VITAGULF', unit: deriveUnit('12 Und * 0.80 Kg') },
    '00096': { client: 'AQUA SEAFOOD LIMITED', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('6 Und * 2 Kg') },
    '00097': { client: 'EVERGLORY INT TRADING (SA) CC', type: 'ENTERO', master: '10 Und * 0.8 Kg', brand: 'JIN PAI', unit: deriveUnit('10 Und * 0.8 Kg') },
    '00098': { client: 'H&N GROUP', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'BLUE RIVER', unit: deriveUnit('10 Und * 4 Lb') },
    '00099': { client: 'EVERGLORY INT TRADING (SA) CC', type: 'COLA', master: '6 Und * 1.80 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00100': { client: 'METRO A.D. EXPORT-IMPORT SKOPJE', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 2 Kg') },
    '00102': { client: 'GALAXY GLOBAL INTERNATIONAL LLC.', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'JIN PAI', unit: deriveUnit('10 Und * 4 Lb') },
    '00103': { client: 'PESCAFACIL S.L.', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00105': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 5 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 5 Lb') },
    '00106': { client: 'ATHANASIOS CHATZISOTIRIOU', type: 'ENTERO', master: '2 Und * 6 Kg', brand: 'VITAGULF', unit: deriveUnit('2 Und * 6 Kg') },
    '00108': { client: 'FAISAL ABDULLA SEAFOOD PROCESSING', type: 'ENTERO', master: '6 Und * 1.80 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00111': { client: 'SUNRISE FOOD TRADING INC', type: 'COLA', master: '10 Und * 2 Lb', brand: 'FISH CREEK', unit: deriveUnit('10 Und * 2 Lb') },
    '00112': { client: 'GROENLANDA SERV SRL', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'VITAGULF', unit: deriveUnit('10 Und * 2 Kg') },
    '00113': { client: 'TAIKA SEAFOOD CORPORATION', type: 'COLA', master: '10 Und * 1.8 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.8 Kg') },
    '00116': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00117': { client: 'PRIMSTAR B.V', type: 'VALOR_AGREGADO', master: '6 Und * 1.80 Kg', brand: 'LIGHT HOUSE', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00119': { client: 'XIANMEILAI FOOD CO., LTD', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'XIANMEILAI', unit: deriveUnit('1 Und * 12 Kg') },
    '00120': { client: 'THALASSA SEAFOODS', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00121': { client: 'THALASSA SEAFOODS', type: 'ENTERO', master: '10 Und * 1.8 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 1.8 Kg') },
    '00122': { client: 'PRIMSTAR B.V', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'LIGHT HOUSE', unit: deriveUnit('6 Und * 2 Kg') },
    '00123': { client: 'MORGAN FOODS INC', type: 'ENTERO', master: '2 Und * 10 Kg', brand: 'SMART FISH', unit: deriveUnit('2 Und * 10 Kg') },
    '00124': { client: 'AXEL FOOD S.R.L', type: 'COLA', master: '10 Und * 1.6 Kg', brand: 'SANTA MARIA ROSSA', unit: deriveUnit('10 Und * 1.6 Kg') },
    '00125': { client: 'MORGAN FOODS INC', type: 'VALOR_AGREGADO', master: '20 Und * 1 Lb', brand: 'SEARAY FOODS', unit: deriveUnit('20 Und * 1 Lb') },
    '00126': { client: 'MORGAN FOODS INC', type: 'ENTERO', master: '5 Und * 4 Lb', brand: 'SEARAY FOODS', unit: deriveUnit('5 Und * 4 Lb') },
    '00127': { client: 'AXEL FOOD S.R.L', type: 'ENTERO', master: '10 Und * 1.9 Kg', brand: 'SANTA MARIA ROSSA', unit: deriveUnit('10 Und * 1.9 Kg') },
    '00128': { client: 'FOOD MASTERS', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00130': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 5 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 5 Lb') },
    '00131': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '6 Und * 2 Kg', brand: 'VITAGULF', unit: deriveUnit('6 Und * 2 Kg') },
    '00133': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 5 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 5 Lb') },
    '00134': { client: 'ACADIAN FISH CO', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 4 Lb') },
    '00136': { client: 'Monarch Trading, LLC', type: 'COLA', master: '10 Und * 4 Lb', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 4 Lb') },
    '00137': { client: 'TAIKA SEAFOOD CORPORATION', type: 'COLA', master: '10 Und * 1.8 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.8 Kg') },
    '00140': { client: 'DAYSEADAY FROZEN B.V.', type: 'ENTERO', master: '12 Und * 0.75 Kg', brand: 'DAYSEADAY', unit: deriveUnit('12 Und * 0.75 Kg') },
    '00142': { client: 'GROENLANDA SERV SRL', type: 'ENTERO', master: '10 Und * 1.6 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 1.6 Kg') },
    '00143': { client: 'GROENLANDA SERV SRL', type: 'COLA', master: '10 Und * 1.6 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 1.6 Kg') },
    '00144': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 2 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Lb') },
    '00145': { client: 'MARUHA NICHIRO CORPORATION', type: 'COLA', master: '6 Und * 1.80 Kg', brand: 'AQUAGOLD', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00146': { client: 'ZUGGS, LLC', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 4 Lb') },
    '00147': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00148': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00149': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00150': { client: 'CENSEA', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'OCEAN GARDEN', unit: deriveUnit('10 Und * 4 Lb') },
    '00152': { client: 'SEA WIN, INC.', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 4 Lb') },
    '00153': { client: 'EAST FISH PROCESSING', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00154': { client: 'EAST FISH PROCESSING', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00155': { client: 'INTEROCEAN SEAFOOD TRADER INC', type: 'COLA', master: '10 Und * 4 Lb', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 4 Lb') },
    '00157': { client: 'FAISAL ABDULLA SEAFOOD PROCESSING', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 2 Kg') },
    '00158': { client: 'ZUGGS, LLC', type: 'ENTERO', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00159': { client: 'ICELAND SEAFOOD IBERICA', type: 'ENTERO', master: '2 Und * 4 Kg', brand: 'OBA', unit: deriveUnit('2 Und * 4 Kg') },
    '00160': { client: 'MABSOUT & IDRISS SAL', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 2 Kg') },
    '00161': { client: 'SIN IMPORTADOR', type: 'COLA', master: '10 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 4 Lb') },
    '00162': { client: 'ICELAND SEAFOOD IBERICA', type: 'COLA', master: '6 Und * 1.7 Kg', brand: 'OBA', unit: deriveUnit('6 Und * 1.7 Kg') },
    '00163': { client: 'FOOD MASTERS', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 2 Kg') },
    '00164': { client: 'VERTIGO SH.P.K', type: 'ENTERO', master: '3 Und * 4 Kg', brand: 'VITAGULF', unit: deriveUnit('3 Und * 4 Kg') },
    '00165': { client: 'UNITED FORTUNE SEAFOOD CORPORATIO', type: 'ENTERO', master: '12 Und* 0.580 Kg', brand: 'VITAGULF', unit: deriveUnit('12 Und* 0.580 Kg') },
    '00166': { client: 'COMAVICOLA', type: 'COLA', master: '6 Und * 2 Kg', brand: 'SANTA MARIA BLU', unit: deriveUnit('6 Und * 2 Kg') },
    '00168': { client: 'COMAVICOLA', type: 'COLA', master: '10 Und * 5 Lb', brand: 'SANTA MARIA BLU', unit: deriveUnit('10 Und * 5 Lb') },
    '00169': { client: 'HAN SEAFOOD, INC.', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'HAN SEAFOOD', unit: deriveUnit('10 Und * 4 Lb') },
    '00170': { client: 'Norven-Scandinavia OÜ', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00171': { client: 'MIANPA S.A.', type: 'COLA', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00172': { client: 'COCEDERO DE MARISCOS', type: 'VALOR_AGREGADO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00173': { client: 'SEA WIN, INC.', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'GANIVA', unit: deriveUnit('10 Und * 4 Lb') },
    '00174': { client: 'NAUTILUS SEAFOOD', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 4 Lb') },
    '00175': { client: 'PESCANOVA HELLAS LTD', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 2 Kg') },
    '00176': { client: 'LAWRENCE WHOLESALE', type: 'COLA', master: '6 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('6 Und * 4 Lb') },
    '00177': { client: 'MIANPA S.A.', type: 'ENTERO', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00178': { client: 'INTEROCEAN SEAFOOD TRADER INC', type: 'ENTERO', master: '6 Und * 4 Lb', brand: 'PRO OCEAN', unit: deriveUnit('6 Und * 4 Lb') },
    '00179': { client: 'OVER SEAS CO', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('6 Und * 2 Kg') },
    '00181': { client: 'SEAFOOD CONNECTION', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('6 Und * 2 Kg') },
    '00182': { client: 'SEAFOOD CONNECTION', type: 'ENTERO', master: '6 Und * 1.6 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('6 Und * 1.6 Kg') },
    '00183': { client: 'DISTRIBUIDORA CAMAVINGA SA DE CV', type: 'COLA', master: '1 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 12 Kg') },
    '00184': { client: 'DISTRIBUIDORA CAMAVINGA SA DE CV', type: 'VALOR_AGREGADO', master: '5 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('5 Und * 2 Kg') },
    '00186': { client: 'CASMARK SEAFOODS LTD', type: 'ENTERO', master: '6 Und * 4 Lb', brand: 'JIN PAI', unit: deriveUnit('6 Und * 4 Lb') },
    '00187': { client: 'SEAFOOD CONNECTION', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('6 Und * 2 Kg') },
    '00192': { client: 'HAI YANG SEAFOOD CO., LTD', type: 'VALOR_AGREGADO', master: '6 Und * 2 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 2 Kg') },
    '00194': { client: 'HAI YANG SEAFOOD CO., LTD', type: 'ENTERO', master: '10 Und * 1.4 Kg', brand: 'JIN PAI', unit: deriveUnit('10 Und * 1.4 Kg') },
    '00195': { client: 'CASMARK SEAFOODS LTD', type: 'COLA', master: '6 Und * 3.6 Lb', brand: 'JIN PAI', unit: deriveUnit('6 Und * 3.6 Lb') },
    '00196': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 2 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Lb') },
    '00197': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 2 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Lb') },
    '00198': { client: 'SAKKYS SEAFOOD TRADING', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 2 Kg') },
    '00199': { client: 'STAR FOOD PRODUCTS, INC.', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'FSB', unit: deriveUnit('10 Und * 4 Lb') },
    '00202': { client: 'COMERCIAL OCEANO LTDA', type: 'COLA', master: '10 Und * 1 Kg', brand: 'CRISTAL', unit: deriveUnit('10 Und * 1 Kg') },
    '00203': { client: 'CENSEA', type: 'COLA', master: '6 Und * 4 Lb', brand: 'APAC', unit: deriveUnit('6 Und * 4 Lb') },
    '00204': { client: 'HEIPLOEG INTERNATIONAL B.V.', type: 'VALOR_AGREGADO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00205': { client: 'HEIPLOEG INTERNATIONAL B.V.', type: 'VALOR_AGREGADO', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00206': { client: 'GROENLANDA SERV SRL', type: 'ENTERO', master: '10 Und * 1.6 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 1.6 Kg') },
    '00207': { client: 'SEAFOOD CONNECTION', type: 'ENTERO', master: '10 Und * 1 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 1 Kg') },
    '00208': { client: 'CENSEA', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'CENSEA', unit: deriveUnit('5 Und * 2 Lb') },
    '00209': { client: 'CENSEA', type: 'COLA', master: '10 Und * 4 Lb', brand: 'OCEAN GARDEN', unit: deriveUnit('10 Und * 4 Lb') },
    '00210': { client: 'CENSEA', type: 'COLA', master: '6 Und * 5 Lb', brand: 'OCEAN GARDEN', unit: deriveUnit('6 Und * 5 Lb') },
    '00211': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 2 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 2 Lb') },
    '00212': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 2 Lb', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Lb') },
    '00213': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '1 Und * 30 Lb', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 30 Lb') },
    '00214': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 30 Lb', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 30 Lb') },
    '00215': { client: 'STAR FOOD PRODUCTS, INC.', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'FSB', unit: deriveUnit('5 Und * 2 Lb') },
    '00216': { client: 'PROMOCEANS INTERNATIONAL LTD', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'SAPHIRE BAY', unit: deriveUnit('5 Und * 2 Lb') },
    '00217': { client: 'TRITON SEA PRODUCTS, INC.', type: 'VALOR_AGREGADO', master: '20 Und * 1 Lb', brand: 'TRITON', unit: deriveUnit('20 Und * 1 Lb') },
    '00218': { client: 'TRITON SEA PRODUCTS, INC.', type: 'VALOR_AGREGADO', master: '4 Und * 5 Lb', brand: 'TRITON', unit: deriveUnit('4 Und * 5 Lb') },
    '00219': { client: 'TRITON SEA PRODUCTS, INC.', type: 'ENTERO', master: '20 Und * 1 Lb', brand: 'TRITON', unit: deriveUnit('20 Und * 1 Lb') },
    '00220': { client: 'SEAFOOD CONNECTION', type: 'ENTERO', master: '12 Und * 0.75 Kg', brand: 'VITAGULF', unit: deriveUnit('12 Und * 0.75 Kg') },
    '00221': { client: 'SEAFOOD CONNECTION', type: 'ENTERO', master: '6 Und * 1.6 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 1.6 Kg') },
    '00222': { client: 'ICELAND SEAFOOD IBERICA', type: 'COLA', master: '10 Und * 1.7 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.7 Kg') },
    '00224': { client: 'ICELAND SEAFOOD IBERICA', type: 'ENTERO', master: '10 Und * 0.9 Kg', brand: 'OBA', unit: deriveUnit('10 Und * 0.9 Kg') },
    '00225': { client: 'ICELAND SEAFOOD IBERICA', type: 'ENTERO', master: '10 Und * 1.9 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 1.9 Kg') },
    '00226': { client: 'ICELAND SEAFOOD IBERICA', type: 'VALOR_AGREGADO', master: '10 Und * 0.75 Kg', brand: 'OBA', unit: deriveUnit('10 Und * 0.75 Kg') },
    '00227': { client: 'ICELAND SEAFOOD IBERICA', type: 'VALOR_AGREGADO', master: '10 Und * 0.75 Kg', brand: 'OBA', unit: deriveUnit('10 Und * 0.75 Kg') },
    '00228': { client: 'ICELAND SEAFOOD IBERICA', type: 'COLA', master: '10 Und * 1.9 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 1.9 Kg') },
    '00229': { client: 'LAWRENCE WHOLESALE', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'VITAGULF', unit: deriveUnit('5 Und * 2 Lb') },
    '00232': { client: 'PESCANOVA HELLAS LTD', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 12 Kg') },
    '00233': { client: 'AL TAHALUF FOOD STUFF AND TRADING WLL', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 2 Kg') },
    '00234': { client: 'PESCANOVA HELLAS LTD', type: 'ENTERO', master: '3 Und * 4 Kg', brand: 'SIN MARCA', unit: deriveUnit('3 Und * 4 Kg') },
    '00235': { client: 'TIANJIN JINFULIN', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'GOLD FULIN', unit: deriveUnit('1 Und * 12 Kg') },
    '00236': { client: 'PESCANOVA INC', type: 'COLA', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00237': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 2 Lb', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Lb') },
    '00238': { client: 'ICELAND SEAFOOD IBERICA', type: 'ENTERO', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00239': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00240': { client: 'LABEYRIE FINE FOODS', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00241': { client: 'BEIRAGEL', type: 'ENTERO', master: '2 Und * 3.9 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 3.9 Kg') },
    '00242': { client: 'BEIRAGEL', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00243': { client: 'IBERICA DE CONGELADOS, S.A.U', type: 'ENTERO', master: '2 Und * 3.9 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 3.9 Kg') },
    '00244': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00245': { client: 'IBERICA DE CONGELADOS, S.A.U', type: 'ENTERO', master: '2 Und * 4.4 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 4.4 Kg') },
    '00246': { client: 'GRUPO PROFAND, S.L.U', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00247': { client: 'INTERNATIONAL SEAFOOD', type: 'COLA', master: '6 Und * 1.6 Kg', brand: 'VITAGULF', unit: deriveUnit('6 Und * 1.6 Kg') },
    '00248': { client: 'BLUE SEA PRODUCTS LLC', type: 'COLA', master: '6 Und * 4 Lb', brand: 'BLUE SEA', unit: deriveUnit('6 Und * 4 Lb') },
    '00249': { client: 'CRUSTA C S.A.S', type: 'COLA', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00250': { client: 'LAWRENCE WHOLESALE', type: 'COLA', master: '10 Und * 4 Lb', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 4 Lb') },
    '00251': { client: 'LAWRENCE WHOLESALE', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'GOLDEN SHRIMP', unit: deriveUnit('5 Und * 2 Lb') },
    '00252': { client: 'LAWRENCE WHOLESALE', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'GOLDEN SHRIMP', unit: deriveUnit('5 Und * 2 Lb') },
    '00253': { client: 'LAWRENCE WHOLESALE', type: 'VALOR_AGREGADO', master: '10 Und * 2 Lb', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Lb') },
    '00254': { client: 'COMAVICOLA', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SANTA MARIA BLU', unit: deriveUnit('6 Und * 2 Kg') },
    '00255': { client: 'SI2A', type: 'ENTERO', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00256': { client: 'PESCAFACIL S.L.', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00258': { client: 'SHAHJALAL FOODS UK LTD', type: 'ENTERO', master: '6 Und * 1.80 Kg', brand: 'SHAHJALAL', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00259': { client: 'PREMIUM FOODS', type: 'ENTERO', master: '10 Und * 3.6 Lb', brand: 'SHAHJALAL', unit: deriveUnit('10 Und * 3.6 Lb') },
    '00261': { client: 'PREMIUM FOODS', type: 'COLA', master: '10 Und * 3.6 Lb', brand: 'SHAHJALAL', unit: deriveUnit('10 Und * 3.6 Lb') },
    '00262': { client: 'HEIPLOEG INTERNATIONAL B.V.', type: 'VALOR_AGREGADO', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00263': { client: 'SN TRADING', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00264': { client: 'VERTIGO SH.P.K', type: 'COLA', master: '10 Und * 1.4 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 1.4 Kg') },
    '00265': { client: 'VERTIGO SH.P.K', type: 'ENTERO', master: '10 Und * 1.4 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 1.4 Kg') },
    '00266': { client: 'LEQUALITY LIFE CO., LTD', type: 'ENTERO', master: '12 Und * 0.6 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('12 Und * 0.6 Kg') },
    '00267': { client: 'PESCANOVA ITALIA SRL', type: 'ENTERO', master: '1 Und * 5.1 Kg', brand: 'RIAZOR', unit: deriveUnit('1 Und * 5.1 Kg') },
    '00268': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00269': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00270': { client: 'IMAEX TRADING CO. INC.', type: 'COLA', master: '10 Und * 4 Lb', brand: 'BEAUTY WING', unit: deriveUnit('10 Und * 4 Lb') },
    '00271': { client: 'NV HOTTLET FROZEN FOODS', type: 'VALOR_AGREGADO', master: '12 Und * 0.80 Kg', brand: 'VITAGULF', unit: deriveUnit('12 Und * 0.80 Kg') },
    '00272': { client: 'COCEDERO DE MARISCOS', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00273': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 12 Kg') },
    '00274': { client: 'FAISAL ABDULLA SEAFOOD PROCESSING', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 2 Kg') },
    '00275': { client: 'MAR&MONTI SRL', type: 'COLA', master: '10 Und * 1.88 Kg', brand: 'MAR&MONTI', unit: deriveUnit('10 Und * 1.88 Kg') },
    '00276': { client: 'ACADIAN FISH CO', type: 'COLA', master: '10 Und * 2 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 2 Lb') },
    '00277': { client: 'BALLINODE SEAFOODS', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00278': { client: 'BALLINODE SEAFOODS', type: 'COLA', master: '6 Und * 0.8 Kg', brand: 'BLUE OCEAN', unit: deriveUnit('6 Und * 0.8 Kg') },
    '00279': { client: 'Bright Springs Foods, LLC', type: 'VALOR_AGREGADO', master: '4 Und * 5 Lb', brand: 'VITAGULF', unit: deriveUnit('4 Und * 5 Lb') },
    '00280': { client: 'COMPESCA S.A.', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 2 Kg') },
    '00281': { client: 'BALLINODE SEAFOODS', type: 'VALOR_AGREGADO', master: '10 Und * 0.7 Kg', brand: 'BLUE OCEAN', unit: deriveUnit('10 Und * 0.7 Kg') },
    '00282': { client: 'BALLINODE SEAFOODS', type: 'VALOR_AGREGADO', master: '6 Und * 0.8 Kg', brand: 'BLUE OCEAN', unit: deriveUnit('6 Und * 0.8 Kg') },
    '00283': { client: 'COMPESCA S.A.', type: 'COLA', master: '10 Und * 1.7 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 1.7 Kg') },
    '00287': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '1 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 12 Kg') },
    '00288': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00290': { client: 'EVERGLORY INT TRADING (SA) CC', type: 'ENTERO', master: '4 Und * 3 Kg', brand: 'SIN MARCA', unit: deriveUnit('4 Und * 3 Kg') },
    '00291': { client: 'NAUTILUS SEAFOOD', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'VITAGULF', unit: deriveUnit('5 Und * 2 Lb') },
    '00292': { client: 'TRUE SEA', type: 'COLA', master: '10 Und * 4 Lb', brand: 'TRUE SEA', unit: deriveUnit('10 Und * 4 Lb') },
    '00293': { client: 'TRUE SEA', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'TRUE SEA', unit: deriveUnit('10 Und * 4 Lb') },
    '00294': { client: 'Congelados Herbania S.A.', type: 'COLA', master: '10 Und * 2 Kg', brand: 'VITAGULF', unit: deriveUnit('10 Und * 2 Kg') },
    '00295': { client: 'Congelados Herbania S.A.', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'VITAGULF', unit: deriveUnit('10 Und * 2 Kg') },
    '00296': { client: 'GOLDEN MAR SEAFOODS', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 12 Kg') },
    '00297': { client: 'GOLDEN MAR SEAFOODS', type: 'COLA', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00298': { client: 'GOLDEN MAR SEAFOODS', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00299': { client: 'ICELAND SEAFOOD IBERICA', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 2 Kg') },
    '00300': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '6 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 2 Kg') },
    '00302': { client: 'TRUE SEA', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'TRUE SEA', unit: deriveUnit('5 Und * 2 Lb') },
    '00303': { client: 'TRUE SEA', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'TRUE SEA', unit: deriveUnit('5 Und * 2 Lb') },
    '00305': { client: 'LANGUS SEAFOOD', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 2 Kg') },
    '00306': { client: 'MENGFU S H L., S L', type: 'VALOR_AGREGADO', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00307': { client: 'MAISON MER', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00308': { client: 'PESCANOVA FRANCE', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00309': { client: 'CAPITAINE HOUAT', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00310': { client: 'BEST CHOICE TRADING CORP', type: 'ENTERO', master: '6 Und * 4 Lb', brand: 'JIN PAI', unit: deriveUnit('6 Und * 4 Lb') },
    '00311': { client: 'BEST CHOICE TRADING CORP', type: 'COLA', master: '6 Und * 4 Lb', brand: 'JIN PAI', unit: deriveUnit('6 Und * 4 Lb') },
    '00312': { client: 'BEST CHOICE TRADING CORP', type: 'VALOR_AGREGADO', master: '10 Und * 1.8 Lb', brand: 'BYC', unit: deriveUnit('10 Und * 1.8 Lb') },
    '00313': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 2 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 2 Lb') },
    '00314': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 2 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 2 Lb') },
    '00315': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 1.814 Kg', brand: 'VITAGULF', unit: deriveUnit('10 Und * 1.814 Kg') },
    '00319': { client: 'AQUAMARINE SEAFOOD', type: 'ENTERO', master: '12 Und * 0.75 Kg', brand: 'VITAGULF', unit: deriveUnit('12 Und * 0.75 Kg') },
    '00321': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00324': { client: 'QUANLIAN AQUATIC PRODUCTS COLLECTION', type: 'ENTERO', master: '10 Und * 1.4 Kg', brand: 'JIN PAI', unit: deriveUnit('10 Und * 1.4 Kg') },
    '00325': { client: 'QUANLIAN AQUATIC PRODUCTS COLLECTION', type: 'ENTERO', master: '10 Und * 1.4 Kg', brand: 'JIN PAI', unit: deriveUnit('10 Und * 1.4 Kg') },
    '00327': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '12 Und * 0.85 Kg', brand: 'SIN MARCA', unit: deriveUnit('12 Und * 0.85 Kg') },
    '00328': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '12 Und * 0.65 Kg', brand: 'SIN MARCA', unit: deriveUnit('12 Und * 0.65 Kg') },
    '00329': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '6 Und * 1.75 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 1.75 Kg') },
    '00331': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '6 Und * 1.65 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 1.65 Kg') },
    '00336': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '6 Und * 1.90 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 1.90 Kg') },
    '00337': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '12 Und * 0.7 Kg', brand: 'CASTELLAR', unit: deriveUnit('12 Und * 0.7 Kg') },
    '00338': { client: 'SEAFOOD CONNECTION', type: 'COLA', master: '10 Und * 1.7 Kg', brand: 'JIN PAI', unit: deriveUnit('10 Und * 1.7 Kg') },
    '00339': { client: 'SEAFOOD CONNECTION', type: 'ENTERO', master: '2 Und * 4 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 4 Kg') },
    '00341': { client: 'Bright Springs Foods, LLC', type: 'VALOR_AGREGADO', master: '4 Und * 5 Lb', brand: 'VITAGULF', unit: deriveUnit('4 Und * 5 Lb') },
    '00343': { client: 'VELES FOODS', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 2 Kg') },
    '00344': { client: 'Marr S.p.A.', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'VITAGULF', unit: deriveUnit('6 Und * 2 Kg') },
    '00346': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00348': { client: 'TIANJIN J-ONE SUPPLY CHAIN MANAGEMENT', type: 'ENTERO', master: '6 Und * 1.5 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 1.5 Kg') },
    '00349': { client: 'GLOBAL GALAXY FOOD SDN BHD', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00350': { client: 'ICELAND SEAFOOD IBERICA', type: 'ENTERO', master: '6 Und * 1.94 Kg', brand: 'PRESTIGE', unit: deriveUnit('6 Und * 1.94 Kg') },
    '00352': { client: 'ICELAND SEAFOOD IBERICA', type: 'ENTERO', master: '6 Und * 1.90 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 1.90 Kg') },
    '00355': { client: 'STAR FOOD PRODUCTS, INC.', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'FSB', unit: deriveUnit('5 Und * 2 Lb') },
    '00357': { client: 'COMAVICOLA', type: 'COLA', master: '10 Und * 5 Lb', brand: 'LUNA BIANCA', unit: deriveUnit('10 Und * 5 Lb') },
    '00358': { client: 'ABAD SEAFOOD LLC.', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 2 Kg') },
    '00359': { client: 'COMAVICOLA', type: 'COLA', master: '10 Und * 5 Lb', brand: 'SANTA MARIA ROSSO', unit: deriveUnit('10 Und * 5 Lb') },
    '00361': { client: 'SEA WIN, INC.', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'BEST', unit: deriveUnit('10 Und * 4 Lb') },
    '00363': { client: 'GOLDEN RICH TRADING CO. LTD.', type: 'ENTERO', master: '6 Und * 4 Lb', brand: 'JIN YUAN', unit: deriveUnit('6 Und * 4 Lb') },
    '00365': { client: 'GOLDEN RICH TRADING CO. LTD.', type: 'ENTERO', master: '6 Und * 4 Lb', brand: 'JIN YUAN', unit: deriveUnit('6 Und * 4 Lb') },
    '00366': { client: 'GAMBASTAR, S.L.', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00368': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'COLA', master: '12 Und * 0.6 Kg', brand: 'SIN MARCA', unit: deriveUnit('12 Und * 0.6 Kg') },
    '00369': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'VALOR_AGREGADO', master: '12 Und * 0.6 Kg', brand: 'SIN MARCA', unit: deriveUnit('12 Und * 0.6 Kg') },
    '00370': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'VALOR_AGREGADO', master: '12 Und * 0.6 Kg', brand: 'SIN MARCA', unit: deriveUnit('12 Und * 0.6 Kg') },
    '00371': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'ENTERO', master: '6 Und * 0.75 Kg', brand: 'ATLANTIC (GREEN)', unit: deriveUnit('6 Und * 0.75 Kg') },
    '00372': { client: 'MARUHA NICHIRO CORPORATION', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('6 Und * 2 Kg') },
    '00373': { client: 'COMPESCA S.A.', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 2 Kg') },
    '00374': { client: 'ICELAND SEAFOOD IBERICA', type: 'VALOR_AGREGADO', master: '10 Und * 0.8 Kg', brand: 'VENTO DI MARE', unit: deriveUnit('10 Und * 0.8 Kg') },
    '00375': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'ENTERO', master: '6 Und * 1.85 Kg', brand: 'OCEAN', unit: deriveUnit('6 Und * 1.85 Kg') },
    '00376': { client: 'BLUE SEA PRODUCTS LLC', type: 'COLA', master: '10 Und * 4 Lb', brand: 'BLUE SEA', unit: deriveUnit('10 Und * 4 Lb') },
    '00377': { client: 'PESCANOVA INC', type: 'VALOR_AGREGADO', master: '6 Und * 5 Lb', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 5 Lb') },
    '00378': { client: 'HEIPLOEG INTERNATIONAL B.V.', type: 'VALOR_AGREGADO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00379': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00381': { client: 'BEST CHOICE TRADING CORP', type: 'COLA', master: '10 Und * 4 Lb', brand: 'BYC', unit: deriveUnit('10 Und * 4 Lb') },
    '00382': { client: 'BEST CHOICE TRADING CORP', type: 'COLA', master: '10 Und * 5 Lb', brand: 'GOLD', unit: deriveUnit('10 Und * 5 Lb') },
    '00383': { client: 'Prime seafood S.L.', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00384': { client: 'ALALAMIA FOR IMPORT & EXPORT', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('6 Und * 2 Kg') },
    '00385': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '6 Und * 1.80 Kg', brand: 'CASTELLAR', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00386': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '6 Und * 1.85 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 1.85 Kg') },
    '00387': { client: 'PRIMSTAR B.V', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'VITAGULF', unit: deriveUnit('1 Und * 12 Kg') },
    '00388': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '6 Und * 1.75 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 1.75 Kg') },
    '00389': { client: 'MARISCOS CASTELLAR S.L.', type: 'ENTERO', master: '12 Und * 0.9 Kg', brand: 'CASTELLAR', unit: deriveUnit('12 Und * 0.9 Kg') },
    '00391': { client: 'SUNRISE FOOD TRADING INC', type: 'COLA', master: '10 Und * 4 Lb', brand: 'VITAGULF', unit: deriveUnit('10 Und * 4 Lb') },
    '00392': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '12 Und * 1 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('12 Und * 1 Kg') },
    '00393': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '12 Und * 1 Kg', brand: 'VITAGULF', unit: deriveUnit('12 Und * 1 Kg') },
    '00394': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 1.5 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.5 Kg') },
    '00395': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 1.5 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.5 Kg') },
    '00396': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 1.5 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.5 Kg') },
    '00397': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 1.5 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.5 Kg') },
    '00398': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 1.5 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.5 Kg') },
    '00399': { client: 'MENGFU S H L., S L', type: 'VALOR_AGREGADO', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00400': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 1.5 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.5 Kg') },
    '00401': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 1.5 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.5 Kg') },
    '00402': { client: 'ShenYang Yisheng Frozen Seafood Co., Ltd', type: 'ENTERO', master: '6 Und * 1.5 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 1.5 Kg') },
    '00403': { client: 'ShenYang Yisheng Frozen Seafood Co., Ltd', type: 'ENTERO', master: '6 Und * 1.80 Kg', brand: 'JIN PAI (PATA ROJA)', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00404': { client: 'ShenYang Yisheng Frozen Seafood Co., Ltd', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'JIN PAI (PATA ROJA)', unit: deriveUnit('1 Und * 12 Kg') },
    '00405': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '1 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('1 Und * 12 Kg') },
    '00408': { client: 'GOLDEN RICH TRADING CO. LTD.', type: 'COLA', master: '6 Und * 3.2 Lb', brand: 'JIN YUAN', unit: deriveUnit('6 Und * 3.2 Lb') },
    '00410': { client: 'EVERGLORY INT TRADING (SA) CC', type: 'COLA', master: '6 Und * 1.80 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00411': { client: 'SENECRUS', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00413': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 1.814 Kg', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 1.814 Kg') },
    '00416': { client: 'HAEWOO SEAFOOD CO., LTD', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('6 Und * 2 Kg') },
    '00417': { client: 'SUPREME SEAFOODS LLC', type: 'VALOR_AGREGADO', master: '6 Und * 5 Lb', brand: 'CROWN', unit: deriveUnit('6 Und * 5 Lb') },
    '00418': { client: 'BEST CHOICE TRADING CORP', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'BYC', unit: deriveUnit('10 Und * 4 Lb') },
    '00419': { client: 'MARISCOS CASTELLAR S.L.', type: 'COLA', master: '10 Und * 1.7 Kg', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 1.7 Kg') },
    '00420': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00423': { client: 'MARUHA NICHIRO CORPORATION', type: 'VALOR_AGREGADO', master: '5 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('5 Und * 2 Kg') },
    '00424': { client: 'MARUHA NICHIRO CORPORATION', type: 'VALOR_AGREGADO', master: '5 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('5 Und * 2 Kg') },
    '00426': { client: 'CAPITAINE HOUAT', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00427': { client: 'Ascania Frozen Foods', type: 'COLA', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00428': { client: 'Ascania Frozen Foods', type: 'ENTERO', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00429': { client: 'Ascania Frozen Foods', type: 'COLA', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00430': { client: 'BLUE SEA PRODUCTS LLC', type: 'VALOR_AGREGADO', master: '10 Und * 2 Lb', brand: 'BLUE SEA', unit: deriveUnit('10 Und * 2 Lb') },
    '00431': { client: 'STE.,HASSAN TRADING CO., SARL', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'AQUAGOLD', unit: deriveUnit('10 Und * 2 Kg') },
    '00432': { client: 'SEAFOOD CONNECTION', type: 'ENTERO', master: '12 Und * 0.75 Kg', brand: 'JIN PAI', unit: deriveUnit('12 Und * 0.75 Kg') },
    '00433': { client: 'AQUAGOLD S.A.', type: 'COLA', master: '10 Und * 2 Kg', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 2 Kg') },
    '00434': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00435': { client: 'BEST CHOICE TRADING CORP', type: 'ENTERO', master: '6 Und * 3.8 Lb', brand: 'GOLD', unit: deriveUnit('6 Und * 3.8 Lb') },
    '00436': { client: 'ANCORA 7 S A', type: 'COLA', master: '10 Und * 1.7 Kg', brand: 'VITAGULF', unit: deriveUnit('10 Und * 1.7 Kg') },
    '00437': { client: 'ANCORA 7 S A', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'VITAGULF', unit: deriveUnit('10 Und * 2 Kg') },
    '00438': { client: 'TAIKA SEAFOOD CORPORATION', type: 'COLA', master: '10 Und * 1.8 Kg', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 1.8 Kg') },
    '00439': { client: 'LAWRENCE WHOLESALE', type: 'COLA', master: '6 Und * 4 Lb', brand: 'GOLDEN SHRIMP', unit: deriveUnit('6 Und * 4 Lb') },
    '00440': { client: 'GALLANT DACHAN', type: 'COLA', master: '10 Und * 1.8 Kg', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 1.8 Kg') },
    '00441': { client: 'ICELAND SEAFOOD IBERICA', type: 'ENTERO', master: '6 Und * 1.80 Kg', brand: 'SEASTAR', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00442': { client: 'Marr S.p.A.', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'STARFISH', unit: deriveUnit('6 Und * 2 Kg') },
    '00444': { client: 'DELFIN ULTRACONGELADOS S.A.', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00445': { client: 'ESCAL SA', type: 'VALOR_AGREGADO', master: '2 Und * 10 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 10 Kg') },
    '00446': { client: 'ESCAL SA', type: 'VALOR_AGREGADO', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00447': { client: 'ICELAND SEAFOOD IBERICA', type: 'ENTERO', master: '6 Und * 1.80 Kg', brand: 'SEASTAR', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00448': { client: 'ICELAND SEAFOOD IBERICA', type: 'COLA', master: '6 Und * 1.80 Kg', brand: 'SEASTAR', unit: deriveUnit('6 Und * 1.80 Kg') },
    '00449': { client: 'TAIKA SEAFOOD CORPORATION', type: 'COLA', master: '10 Und * 1.8 Kg', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 1.8 Kg') },
    '00450': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'VALOR_AGREGADO', master: '12 Und * 0.80 Kg', brand: 'OCEAN', unit: deriveUnit('12 Und * 0.80 Kg') },
    '00451': { client: 'C.P. Food Products INC (BUYER)', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'Captain\'s Catch', unit: deriveUnit('5 Und * 2 Lb') },
    '00452': { client: 'C.P. Food Products INC (BUYER)', type: 'VALOR_AGREGADO', master: '4 Und * 5 Lb', brand: 'Captain\'s Catch', unit: deriveUnit('4 Und * 5 Lb') },
    '00453': { client: 'Marr S.p.A.', type: 'COLA', master: '6 Und * 2 Kg', brand: 'STARFISH', unit: deriveUnit('6 Und * 2 Kg') },
    '00454': { client: 'SEAFOOD TRADING COMPANY SARL', type: 'VALOR_AGREGADO', master: '12 Und * 0.8 Kg', brand: 'OCEAN', unit: deriveUnit('12 Und * 0.8 Kg') },
    '00457': { client: 'SENECRUS', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 12 Kg') },
    '00458': { client: 'VASILIS SAVRAMIS', type: 'ENTERO', master: '3 Und * 4 Kg', brand: 'SANTA MARINA', unit: deriveUnit('3 Und * 4 Kg') },
    '00459': { client: 'HEIPLOEG INTERNATIONAL B.V.', type: 'COLA', master: '2 Und * 12 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('2 Und * 12 Kg') },
    '00460': { client: 'ACADIAN FISH CO', type: 'VALOR_AGREGADO', master: '5 Und * 2 Lb', brand: 'VITAGULF', unit: deriveUnit('5 Und * 2 Lb') },
    '00462': { client: 'THALASSA SEAFOODS', type: 'ENTERO', master: '10 Und * 1.8 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 1.8 Kg') },
    '00464': { client: 'THALASSA SEAFOODS', type: 'VALOR_AGREGADO', master: '10 Und * 0.8 Kg', brand: 'SEA', unit: deriveUnit('10 Und * 0.8 Kg') },
    '00466': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'VITAGULF', unit: deriveUnit('1 Und * 12 Kg') },
    '00469': { client: 'SINGULAR SEA S.L.', type: 'COLA', master: '10 Und * 1.7 Kg', brand: 'SINGULAR', unit: deriveUnit('10 Und * 1.7 Kg') },
    '00470': { client: 'PESCAFACIL S.L.', type: 'VALOR_AGREGADO', master: '1 Und * 12 Kg', brand: 'JINFULIN', unit: deriveUnit('1 Und * 12 Kg') },
    '00471': { client: 'THALASSA SEAFOODS', type: 'ENTERO', master: '10 Und * 0.75 Kg', brand: 'VITAGULF', unit: deriveUnit('10 Und * 0.75 Kg') },
    '00472': { client: 'PESCANOVA INC', type: 'COLA', master: '10 Und * 4 Lb', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 4 Lb') },
    '00473': { client: 'VASILIS SAVRAMIS', type: 'ENTERO', master: '3 Und * 4 Kg', brand: 'SIN MARCA', unit: deriveUnit('3 Und * 4 Kg') },
    '00474': { client: 'GALAXY GLOBAL INTERNATIONAL LLC.', type: 'VALOR_AGREGADO', master: '5 Und * 1.9 Lb', brand: 'SIN MARCA', unit: deriveUnit('5 Und * 1.9 Lb') },
    '00475': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00476': { client: 'BARRUFET SEAFOOD SL', type: 'COLA', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00477': { client: 'BARRUFET SEAFOOD SL', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00480': { client: 'CONFREMAR', type: 'COLA', master: '10 Und * 1.7 Kg', brand: 'VITAGULF', unit: deriveUnit('10 Und * 1.7 Kg') },
    '00481': { client: 'CONSIGNACIONES DEL MAR, SA', type: 'COLA', master: '10 Und * 1.7 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1.7 Kg') },
    '00482': { client: 'VASILIS SAVRAMIS', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SANTA MARINA', unit: deriveUnit('6 Und * 2 Kg') },
    '00483': { client: 'DELFIN ULTRACONGELADOS S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('1 Und * 12 Kg') },
    '00484': { client: 'HN GROUP', type: 'VALOR_AGREGADO', master: '10 Und * 2 Lb', brand: 'BLUE RIVER', unit: deriveUnit('10 Und * 2 Lb') },
    '00487': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00488': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00489': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00490': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00491': { client: 'CRUSTA C S.A.S', type: 'ENTERO', master: '2 Und * 12 Kg', brand: 'AQUAGOLD', unit: deriveUnit('2 Und * 12 Kg') },
    '00493': { client: 'THE DEEP SEAFOOD CO LLC', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'VITAGULF', unit: deriveUnit('6 Und * 2 Kg') },
    '00494': { client: 'GALAXY GLOBAL INTERNATIONAL LLC.', type: 'ENTERO', master: '10 Und * 4 Lb', brand: 'JIN PAI', unit: deriveUnit('10 Und * 4 Lb') },
    '00495': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'JIN PAI', unit: deriveUnit('1 Und * 12 Kg') },
    '00496': { client: 'MIRA ROYAL DOO', type: 'COLA', master: '10 Und * 2 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 2 Kg') },
    '00497': { client: 'Ascania Frozen Foods', type: 'COLA', master: '10 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 2 Kg') },
    '00498': { client: 'Hengsheng Heyuan Economic and trade', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'BZ DRAGON', unit: deriveUnit('1 Und * 12 Kg') },
    '00499': { client: 'TIANJIN J-ONE SUPPLY CHAIN MANAGEMENT', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('1 Und * 12 Kg') },
    '00500': { client: 'SEAFOOD CONNECTION', type: 'VALOR_AGREGADO', master: '10 Und * 0.75 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 0.75 Kg') },
    '00501': { client: 'OKEANOS P.C.', type: 'ENTERO', master: '10 Und * 2 Kg', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 2 Kg') },
    '00502': { client: 'LEQUALITY LIFE CO., LTD', type: 'ENTERO', master: '12 Und * 0.65 Kg', brand: 'JIN PAI', unit: deriveUnit('12 Und * 0.65 Kg') },
    '00503': { client: 'OKEANOS P.C.', type: 'ENTERO', master: '6 Und * 2 Kg', brand: 'SIN MARCA', unit: deriveUnit('6 Und * 2 Kg') },
    '00504': { client: 'SEA WIN, INC.', type: 'COLA', master: '10 Und * 4 Lb', brand: 'GANIVA', unit: deriveUnit('10 Und * 4 Lb') },
    '00506': { client: 'TIANJIN J-ONE SUPPLY CHAIN MANAGEMENT', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'RED TIGER', unit: deriveUnit('1 Und * 12 Kg') },
    '00507': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 1 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1 Kg') },
    '00508': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '10 Und * 1 Kg', brand: 'SIN MARCA', unit: deriveUnit('10 Und * 1 Kg') },
    '00510': { client: 'FRESH&GOOD OÜ', type: 'COLA', master: '1 Und * 12 Kg', brand: 'GOLD FULIN', unit: deriveUnit('1 Und * 12 Kg') },
    '00511': { client: 'THALASSA SEAFOODS', type: 'COLA', master: '10 Und * 1.7 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 1.7 Kg') },
    '00514': { client: 'YUAN SYIN TRADING CO., LTD', type: 'ENTERO', master: '12 Und * 0.6 Kg', brand: 'VITAGULF', unit: deriveUnit('12 Und * 0.6 Kg') },
    '00515': { client: 'TIANJIN J-ONE SUPPLY CHAIN MANAGEMENT CO., LTD', type: 'ENTERO', master: '6 Und * 1.5 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 1.5 Kg') },
    '00516': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '6 Und * 1.5 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 1.5 Kg') },
    '00517': { client: 'Bright Springs Foods, LLC', type: 'VALOR_AGREGADO', master: '4 Und * 5 Lb', brand: 'VITAGULF', unit: deriveUnit('4 Und * 5 Lb') },
    '00509': { client: 'SEAFOOD CONNECTION', type: 'ENTERO', master: '10 Und * 0.85 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('10 Und * 0.85 Kg') },
    '00513': { client: 'GEM OCEAN SEAFOOD CORPORATION', type: 'ENTERO', master: '12 Und * 0.65 Kg', brand: 'AQUA MARIS', unit: deriveUnit('12 Und * 0.65 Kg') },
    '00518': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '10 Und * 1.4 Kg', brand: 'JIN PAI', unit: deriveUnit('10 Und * 1.4 Kg') },
    '00519': { client: 'AQUAGOLD S.A.', type: 'ENTERO', master: '1 Und * 12 Kg', brand: 'GOLDEN SHRIMP', unit: deriveUnit('1 Und * 12 Kg') },
    '00521': { client: 'GALLANT DACHAN', type: 'COLA', master: '10 Und * 1.814 Kg', brand: 'AQUA MARIS', unit: deriveUnit('10 Und * 1.814 Kg') },
    '00523': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00524': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00539': { client: 'SUPREME SEAFOODS LLC', type: 'VALOR_AGREGADO', master: '10 Und * 5 Lb', brand: 'CROWN', unit: deriveUnit('10 Und * 5 Lb') },
    '00544': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00547': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00548': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00549': { client: 'AQUAGOLD S.A.', type: 'VALOR_AGREGADO', master: '2 Und * 20 Lb', brand: 'SIN MARCA', unit: deriveUnit('2 Und * 20 Lb') },
    '00555': { client: 'SIN IMPORTADOR', type: 'ENTERO', master: '6 Und * 1.5 Kg', brand: 'JIN PAI', unit: deriveUnit('6 Und * 1.5 Kg') },
};
