import { useEffect } from 'react';
import { toast } from 'sonner';
import { logger } from '@/lib/logger';

export function useServiceWorker() {
    useEffect(() => {
        if (typeof window === 'undefined' || !('serviceWorker' in navigator)) {
            return;
        }

        // Register service worker generated by next-pwa
        const registerSW = async () => {
            try {
                const registration = await navigator.serviceWorker.register('/sw.js', {
                    scope: '/'
                });

                logger.log('Service Worker registrado exitosamente');

                // Listen for updates
                registration.addEventListener('updatefound', () => {
                    const newWorker = registration.installing;

                    if (!newWorker) return;

                    newWorker.addEventListener('statechange', () => {
                        if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                            // New service worker is ready
                            toast.info('Nueva versión disponible', {
                                description: 'Actualiza para ver los últimos cambios',
                                action: {
                                    label: 'Actualizar',
                                    onClick: () => {
                                        newWorker.postMessage({ type: 'SKIP_WAITING' });
                                        window.location.reload();
                                    }
                                },
                                duration: Infinity,
                            });
                        }
                    });
                });

                // Handle controller change (new SW activated)
                navigator.serviceWorker.addEventListener('controllerchange', () => {
                    logger.log('Service Worker actualizado, recargando...');
                });

            } catch (error) {
                console.error('Error registrando Service Worker:', error);
            }
        };

        registerSW();

        // Cleanup
        return () => {};
    }, []);
}
