import { useEffect } from 'react';
import { toast } from 'sonner';
import { logger } from '@/lib/logger';

export function useServiceWorker() {
    useEffect(() => {
        if (typeof window === 'undefined' || !('serviceWorker' in navigator)) {
            return;
        }

        // Register service worker generated by next-pwa
        const registerSW = async () => {
            try {
                const registration = await navigator.serviceWorker.register('/sw.js', {
                    scope: '/'
                });

                logger.log('Service Worker registrado exitosamente');

                // Listen for updates
                registration.addEventListener('updatefound', () => {
                    const newWorker = registration.installing;

                    if (!newWorker) return;

                    newWorker.addEventListener('statechange', () => {
                        if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                            // New service worker is ready
                            toast.info('Nueva versión disponible', {
                                description: 'Actualiza para ver los últimos cambios',
                                action: {
                                    label: 'Actualizar',
                                    onClick: () => {
                                        newWorker.postMessage({ type: 'SKIP_WAITING' });
                                        window.location.reload();
                                    }
                                },
                                duration: Infinity,
                            });
                        }
                    });
                });

                // Handle controller change (new SW activated)
                navigator.serviceWorker.addEventListener('controllerchange', () => {
                    logger.log('Service Worker actualizado, recargando...');
                });

            } catch (error) {
                console.error('Error registrando Service Worker:', error);
            }
        };

        registerSW();

        // ✅ PERIODIC BACKGROUND CHECK FOR PENDING PHOTOS
        // This ensures photos get uploaded even if the user misses the 'online' event
        const checkPendingPhotos = async () => {
            if (!navigator.onLine) return;

            try {
                const { photoStorageService } = await import('@/lib/photoStorageService');
                await photoStorageService.initialize();

                const [pending, failed] = await Promise.all([
                    photoStorageService.getPendingPhotos(),
                    photoStorageService.getFailedPhotos()
                ]);

                const totalPending = pending.length + failed.length;

                if (totalPending > 0) {
                    logger.log(`📋 Background check: ${totalPending} fotos pendientes detectadas`);
                    // The PendingUploadsPanel will handle the actual retry
                    // This is just to ensure visibility in logs
                }
            } catch (error) {
                console.error('Error en background check de fotos:', error);
            }
        };

        // Check every 30 seconds
        const photoCheckInterval = setInterval(checkPendingPhotos, 30000);

        // Cleanup
        return () => {
            clearInterval(photoCheckInterval);
        };
    }, []);
}
